<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ngi thn hin l nhn vin C Quan_data.userfamiliar.9e8fe47a-4f77-4799-a0a3-84ca0c648b8c.is_cq_staff</name>
   <tag></tag>
   <elementGuidId>ae7cae80-a1c7-4ade-bf81-988ef7808aeb</elementGuidId>
   <imagePath>Screenshots/Targets/Page_H s c nhn - H thng ni b C Quan PTGL/button_Ngi thn hin l nhn vin C Quan_data.userfamiliar.9e8fe47a-4f77-4799-a0a3-84ca0c648b8c.is_cq_staff.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-thong-tin-gia-dinh-tab']/div/div/div/div/div[2]/div/ul/div/li/div[2]/div/div/div/div/div[2]/button</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_H s c nhn - H thng ni b C Quan PTGL/button_Ngi thn hin l nhn vin C Quan_data.userfamiliar.9e8fe47a-4f77-4799-a0a3-84ca0c648b8c.is_cq_staff.png</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>76a52b93-346a-482f-b809-86150f42d68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-data</name>
      <type>Main</type>
      <value>{
                state: $wire.$entangle('data.userfamiliar.9e8fe47a-4f77-4799-a0a3-84ca0c648b8c.is_cq_staff', true),
            }</value>
      <webElementGuid>1d865a69-8857-4e09-840c-7079ebae8d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-bind:aria-checked</name>
      <type>Main</type>
      <value>state?.toString()</value>
      <webElementGuid>ce37cdbf-23f3-4353-bb93-2312f5ff632c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-on:click</name>
      <type>Main</type>
      <value>state = ! state</value>
      <webElementGuid>08e6faff-3cf5-44cb-887d-066927bca4ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-bind:class</name>
      <type>Main</type>
      <value>
                state
                    ? 'fi-color-custom bg-custom-600'
                    : 'fi-color-gray bg-gray-200 dark:bg-gray-700'
            </value>
      <webElementGuid>afa9b9b3-a492-4996-963e-62e8cd388426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-bind:style</name>
      <type>Main</type>
      <value>
                state
                    ? '--c-600:var(--success-600)'
                    : '--c-600:var(--gray-600)'
            </value>
      <webElementGuid>eac600a8-b911-49c1-ace5-806a85bbfc49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-fo-toggle relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border-2 border-transparent outline-none transition-colors duration-200 ease-in-out disabled:pointer-events-none disabled:opacity-70 fi-color-gray bg-gray-200 dark:bg-gray-700</value>
      <webElementGuid>0effe387-4633-48f6-bbe9-5df29361cbbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a585d942-08a6-4fb5-b4c7-dab85d3426d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data.userfamiliar.9e8fe47a-4f77-4799-a0a3-84ca0c648b8c.is_cq_staff</value>
      <webElementGuid>6b3dacb0-be46-43b6-9727-73195c805887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>67908131-4dc2-4fef-9bff-eb73c781c580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97e78068-a8df-4932-bc8a-8e19f5210f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:loading.attr</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>c21b73e5-d907-4f31-b23a-f1af89be69db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:target</name>
      <type>Main</type>
      <value>data.userfamiliar.9e8fe47a-4f77-4799-a0a3-84ca0c648b8c.is_cq_staff</value>
      <webElementGuid>107e5910-438d-46cf-b4e0-63e7ea04ed3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data.userfamiliar.9e8fe47a-4f77-4799-a0a3-84ca0c648b8c.is_cq_staff&quot;)</value>
      <webElementGuid>7e867dd8-c8a1-4034-834e-d8514ed9a955</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='data.userfamiliar.9e8fe47a-4f77-4799-a0a3-84ca0c648b8c.is_cq_staff']</value>
      <webElementGuid>cf6e8bd6-55f7-48b3-8cab-13da411f2491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='-thong-tin-gia-dinh-tab']/div/div/div/div/div[2]/div/ul/div/li/div[2]/div/div/div/div/div[2]/button</value>
      <webElementGuid>8e95786d-56c1-4dbf-b262-143fe40585d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/button</value>
      <webElementGuid>dd4f38f3-0ffd-466f-b6b5-3de139770fe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'data.userfamiliar.9e8fe47a-4f77-4799-a0a3-84ca0c648b8c.is_cq_staff' and @type = 'button']</value>
      <webElementGuid>f3393f43-71c3-492c-858f-6d5c632a4fa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
