<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_kynangtinhoc</name>
   <tag></tag>
   <elementGuidId>cba6326a-e6c5-4a1f-981a-35e2af70debb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='data.kynangtinhoc-Có bằng cấp, chứng chỉ về tin học']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6690e64e-c895-403e-b39d-45e98fe890fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data.kynangtinhoc-Có bằng cấp, chứng chỉ về tin học</value>
      <webElementGuid>ca3a7f47-c1f6-4201-862a-4b73321bbacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data.kynangtinhoc</value>
      <webElementGuid>7f8ac1d0-7731-4ae3-ab79-dc828ed86a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>40cf6766-ea99-4803-b5ad-bc829be026de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Có bằng cấp, chứng chỉ về tin học</value>
      <webElementGuid>f2ec7721-2a5f-49d7-ba4d-21ecf9d4405b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:loading.attr</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>a07a0d6c-1810-424a-8cb8-966f2093c4dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model</name>
      <type>Main</type>
      <value>data.kynangtinhoc</value>
      <webElementGuid>72e4246b-d5e7-410b-a429-7286af2ccb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 border-none bg-white shadow-sm ring-1 transition duration-75 checked:ring-0 focus:ring-2 focus:ring-offset-0 disabled:bg-gray-50 disabled:text-gray-50 disabled:checked:bg-current disabled:checked:text-gray-400 dark:bg-white/5 dark:disabled:bg-transparent dark:disabled:checked:bg-gray-600 text-primary-600 ring-gray-950/10 focus:ring-primary-600 checked:focus:ring-primary-500/50 dark:text-primary-500 dark:ring-white/20 dark:checked:bg-primary-500 dark:focus:ring-primary-500 dark:checked:focus:ring-primary-400/50 dark:disabled:ring-white/10</value>
      <webElementGuid>3f1715d4-1eb1-49bc-974f-086d63af1d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data.kynangtinhoc-Có bằng cấp, chứng chỉ về tin học&quot;)</value>
      <webElementGuid>3cadc445-2d16-447f-a2e1-fde5af482c94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='data.kynangtinhoc-Có bằng cấp, chứng chỉ về tin học']</value>
      <webElementGuid>41fc7b1e-b2e7-4543-9c7d-e1088d36ab43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='data.ky-nang-tin-hoc']/div/div/div/div/div/div/div[2]/div/div[3]/label/input</value>
      <webElementGuid>007c6c53-d854-484a-acef-6ff035aaab14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/section/div/div/div/div/div/div/div[2]/div/div[3]/label/input</value>
      <webElementGuid>f40345d2-3e80-436d-964c-38238484eb87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'data.kynangtinhoc-Có bằng cấp, chứng chỉ về tin học' and @name = 'data.kynangtinhoc' and @type = 'radio']</value>
      <webElementGuid>b60bca03-8109-4804-933e-23f80027db7b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
