<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Me</name>
   <tag></tag>
   <elementGuidId>a7647381-29cd-4adc-8356-1db813022ec0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choices--datauserfamiliar6252bd91-09b0-4ad9-9ea6-62661e5937c8relationship-item-choice-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-thong-tin-gia-dinh-tab']/div/div/div/div/div[2]/div/ul/div/li/div[2]/div/div[2]/fieldset/div/div/div/div/div[2]/div/div/div/div/div[2]/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b177a64-f2ed-4d5b-8059-5c4f4c9d2e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choices--datauserfamiliar6252bd91-09b0-4ad9-9ea6-62661e5937c8relationship-item-choice-2</value>
      <webElementGuid>97e67d4d-d007-453f-8c4d-6d56080dff81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>choices__item choices__item--choice choices__item--selectable is-highlighted</value>
      <webElementGuid>c186fcb7-50ac-4e86-b948-fe92529ca680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>81f75601-9ee7-4c00-9d70-4c2f8aa537b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>a388f096-4754-41c6-b9bf-70450a408ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Mẹ</value>
      <webElementGuid>36092896-081c-41e3-8b86-5b847eccf315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3f09abbd-4945-459f-9bc0-b1189c8e69eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mẹ</value>
      <webElementGuid>535bf3c4-78aa-4e5a-9124-dc7c1ccde7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choices--datauserfamiliar6252bd91-09b0-4ad9-9ea6-62661e5937c8relationship-item-choice-2&quot;)</value>
      <webElementGuid>eb9c9662-dd55-46c8-8c82-3e5d8f8075f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='choices--datauserfamiliar6252bd91-09b0-4ad9-9ea6-62661e5937c8relationship-item-choice-2']</value>
      <webElementGuid>03be812a-e8c9-4573-8efe-5cb37a1928df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='-thong-tin-gia-dinh-tab']/div/div/div/div/div[2]/div/ul/div/li/div[2]/div/div[2]/fieldset/div/div/div/div/div[2]/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>e951e1fa-ece5-488b-bfbf-bc4c6c269b4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div[2]</value>
      <webElementGuid>1e2bd6fa-7ee5-4b79-b872-7094e948e5fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'choices--datauserfamiliar6252bd91-09b0-4ad9-9ea6-62661e5937c8relationship-item-choice-2' and (text() = 'Mẹ' or . = 'Mẹ')]</value>
      <webElementGuid>36ae8595-6ac9-4446-9315-dceec423d4ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
