<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Cha</name>
   <tag></tag>
   <elementGuidId>2e713d56-0b35-4a9e-94b0-de7b1485382e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#choices--datauserfamiliar94cf6429-c618-48c2-95fd-f78b2feb10d0relationship-item-choice-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-thong-tin-gia-dinh-tab']/div/div/div/div/div[2]/div/ul/div/li[2]/div[2]/div/div[3]/fieldset/div/div[2]/div/div/div[2]/div/div/div/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>98d923c5-64ac-46fa-b1ea-fba2f49ce9f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>choices--datauserfamiliar94cf6429-c618-48c2-95fd-f78b2feb10d0relationship-item-choice-1</value>
      <webElementGuid>30270b63-5109-4920-9c10-616487c72632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>choices__item choices__item--choice choices__item--selectable is-highlighted</value>
      <webElementGuid>d72a9c63-816d-4702-975b-f316965e8b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>2fa4e7ea-ac1c-4c46-89cd-b4ee6d428b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>23697b48-a645-482d-8ed1-70be3b7c1b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>Cha</value>
      <webElementGuid>649a0307-0eb4-4d0b-b9db-c49f1b6672b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c9b1b1a3-ba76-47c1-b417-092636809f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cha</value>
      <webElementGuid>53b55be9-7006-48c9-9000-1e82d5bbf82d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;choices--datauserfamiliar94cf6429-c618-48c2-95fd-f78b2feb10d0relationship-item-choice-1&quot;)</value>
      <webElementGuid>310519e8-a093-4a63-8913-03ff081e055e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='choices--datauserfamiliar94cf6429-c618-48c2-95fd-f78b2feb10d0relationship-item-choice-1']</value>
      <webElementGuid>a6d2e590-5bca-4eeb-a16d-38e67bb1a80f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='-thong-tin-gia-dinh-tab']/div/div/div/div/div[2]/div/ul/div/li[2]/div[2]/div/div[3]/fieldset/div/div[2]/div/div/div[2]/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>c69f0df3-f50d-4cf6-a681-730b03f27b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/div/div[2]/div/div/div[2]/div/div/div/div/div[2]/div/div</value>
      <webElementGuid>7a957dad-c2a5-4cc5-bca3-a6752f9fc209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'choices--datauserfamiliar94cf6429-c618-48c2-95fd-f78b2feb10d0relationship-item-choice-1' and (text() = 'Cha' or . = 'Cha')]</value>
      <webElementGuid>0b0e84e5-5678-4d74-adcc-31481418a003</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
