<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__data.userfamiliar_Ngaysinh</name>
   <tag></tag>
   <elementGuidId>de281be4-efa8-4abb-a2e5-a3b3a73b554e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-thong-tin-gia-dinh-tab']/div/div/div/div/div[2]/div/ul/div/li[2]/div[2]/div/div[3]/fieldset/div/div[4]/div/div/div[2]/div/div/div/button/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7a60bd46-be95-48e6-967d-a2746aa10f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MM/DD/YYYY</value>
      <webElementGuid>b7c34089-c2d6-4f73-affc-d1589332cea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:key</name>
      <type>Main</type>
      <value>tH4PVWisvGtTDIFy4XBo.data.userfamiliar.74696e2e-c725-41c0-a0fa-cc251b5c0177.ngaysinh.Filament\Forms\Components\DatePicker.display-text</value>
      <webElementGuid>9d247685-b738-4236-b547-f10c2b6352bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-model</name>
      <type>Main</type>
      <value>displayText</value>
      <webElementGuid>5e625dbd-1342-4b89-a732-0eddecd1481e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data.userfamiliar.74696e2e-c725-41c0-a0fa-cc251b5c0177.ngaysinh</value>
      <webElementGuid>7cb3f886-5813-4540-b7b4-ebdf3cf9b57b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full border-none bg-transparent px-3 py-1.5 text-base text-gray-950 outline-none transition duration-75 placeholder:text-gray-400 focus:ring-0 disabled:text-gray-500 disabled:[-webkit-text-fill-color:theme(colors.gray.500)] dark:text-white dark:placeholder:text-gray-500 dark:disabled:text-gray-400 dark:disabled:[-webkit-text-fill-color:theme(colors.gray.400)] sm:text-sm sm:leading-6</value>
      <webElementGuid>398448f9-de35-49a0-8db9-8f87de9b3e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data.userfamiliar.74696e2e-c725-41c0-a0fa-cc251b5c0177.ngaysinh&quot;)</value>
      <webElementGuid>c6dfb5ed-3d2a-4b46-885c-35b2229534ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='data.userfamiliar.74696e2e-c725-41c0-a0fa-cc251b5c0177.ngaysinh']</value>
      <webElementGuid>15f4bc2d-4d3a-41c2-8688-a28f76e4333d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='-thong-tin-gia-dinh-tab']/div/div/div/div/div[2]/div/ul/div/li[2]/div[2]/div/div[3]/fieldset/div/div[4]/div/div/div[2]/div/div/div/button/input</value>
      <webElementGuid>4fb11097-9829-482d-8a73-d2b94ed60867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[2]/div/div/div/button/input</value>
      <webElementGuid>d438f573-e9b0-487c-8358-c3069a395a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'MM/DD/YYYY' and @id = 'data.userfamiliar.74696e2e-c725-41c0-a0fa-cc251b5c0177.ngaysinh']</value>
      <webElementGuid>d5176ec2-bca6-498c-9046-c243111d3782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
