<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__data.userfamiliar_Phone</name>
   <tag></tag>
   <elementGuidId>6ce4e82d-ef96-4fb9-8ce7-dba8a7a96811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='-thong-tin-gia-dinh-tab']/div/div/div/div/div[2]/div/ul/div/li[2]/div[2]/div/div[3]/fieldset/div/div[6]/div/div/div[2]/div/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42c61e03-6309-436b-8047-766953651add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-input block w-full border-none py-1.5 text-base text-gray-950 transition duration-75 placeholder:text-gray-400 focus:ring-0 disabled:text-gray-500 disabled:[-webkit-text-fill-color:theme(colors.gray.500)] disabled:placeholder:[-webkit-text-fill-color:theme(colors.gray.400)] dark:text-white dark:placeholder:text-gray-500 dark:disabled:text-gray-400 dark:disabled:[-webkit-text-fill-color:theme(colors.gray.400)] dark:disabled:placeholder:[-webkit-text-fill-color:theme(colors.gray.500)] sm:text-sm sm:leading-6 bg-white/0 ps-3 pe-3</value>
      <webElementGuid>6b55fbfb-ab2b-49d8-ae8d-753b5ce9c6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data.userfamiliar.98620827-73bd-42ee-894f-5d910b3a0cfd.phone</value>
      <webElementGuid>431bc35f-017c-4094-99be-6bc010ac4d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d52f00e7-7f07-4d54-8c19-27ee83ba5921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model</name>
      <type>Main</type>
      <value>data.userfamiliar.98620827-73bd-42ee-894f-5d910b3a0cfd.phone</value>
      <webElementGuid>41e96838-b0fc-4f37-8067-76ba453c2db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-data</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>0f22ef7a-f296-4702-8ff1-6fd0ab84d18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-mask</name>
      <type>Main</type>
      <value>9999999999</value>
      <webElementGuid>ddc2be50-57a4-443f-8874-f74633af91a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-has-alpine-state</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ff38c466-c9f0-4b92-814d-1aaba1f34712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data.userfamiliar.98620827-73bd-42ee-894f-5d910b3a0cfd.phone&quot;)</value>
      <webElementGuid>4d089564-602d-4521-8bfb-745ee1327445</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='data.userfamiliar.98620827-73bd-42ee-894f-5d910b3a0cfd.phone']</value>
      <webElementGuid>bd2ac4a7-582d-44de-be2e-1163132f27e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='-thong-tin-gia-dinh-tab']/div/div/div/div/div[2]/div/ul/div/li[2]/div[2]/div/div[3]/fieldset/div/div[6]/div/div/div[2]/div/div/input</value>
      <webElementGuid>ecbdc4b3-5ca8-45e4-a38b-e80a7f705c44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div[6]/div/div/div[2]/div/div/input</value>
      <webElementGuid>932cd8ad-81a4-4b69-9d90-7853cd03504c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'data.userfamiliar.98620827-73bd-42ee-894f-5d910b3a0cfd.phone' and @type = 'text']</value>
      <webElementGuid>837de882-d63a-436c-96d1-265bc54a4260</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
