<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttondata_hasKiemNhiem</name>
   <tag></tag>
   <elementGuidId>ab11e72f-40b5-41ac-8b8b-e1ce0460e0bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='data.hasConcurrentWork']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02ac3011-ee59-4567-a1f2-6c1f1be6cf1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-data</name>
      <type>Main</type>
      <value>{
                state: $wire.$entangle('data.hasConcurrentWork', true),
            }</value>
      <webElementGuid>c84aa1eb-e177-4721-bcd8-b81b938a95d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-bind:aria-checked</name>
      <type>Main</type>
      <value>state?.toString()</value>
      <webElementGuid>333f3194-2f59-43e7-a309-a04129eda2ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-on:click</name>
      <type>Main</type>
      <value>state = ! state</value>
      <webElementGuid>382ca7d5-512f-4176-8c3a-11f4bc7358d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-bind:class</name>
      <type>Main</type>
      <value>
                state
                    ? 'fi-color-custom bg-custom-600'
                    : 'fi-color-gray bg-gray-200 dark:bg-gray-700'
            </value>
      <webElementGuid>589d6e6a-1378-4f23-9e3b-584ac917a752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-bind:style</name>
      <type>Main</type>
      <value>
                state
                    ? '--c-600:var(--success-600)'
                    : '--c-600:var(--gray-600)'
            </value>
      <webElementGuid>5ad2bc44-5727-4de9-9100-970703898e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-fo-toggle relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full border-2 border-transparent outline-none transition-colors duration-200 ease-in-out disabled:pointer-events-none disabled:opacity-70 fi-color-gray bg-gray-200 dark:bg-gray-700</value>
      <webElementGuid>95004f30-6b03-435d-8d5e-2c4e2f05594e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1e6cf3a0-4b33-4880-afcc-753a4921f826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data.hasConcurrentWork</value>
      <webElementGuid>c11e31be-3793-4f79-87d8-456353d7fc4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>switch</value>
      <webElementGuid>73076bb3-165b-46c7-93de-0bdb891320e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3c255384-5e73-4b0d-9c8e-4269aa953563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:loading.attr</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>e060ba4e-a0f1-4409-b999-a7aac9c2e94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:target</name>
      <type>Main</type>
      <value>data.hasConcurrentWork</value>
      <webElementGuid>9cefcce6-bf04-4033-9a8b-2fd037d5328c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-has-alpine-state</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b049ec0d-24af-49dc-8dc9-568d5072f91c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data.hasConcurrentWork&quot;)</value>
      <webElementGuid>512f50c5-4635-441e-a27f-4a2d128d943a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='data.hasConcurrentWork']</value>
      <webElementGuid>afd64375-5f87-424e-9e0c-5e95aded5028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dang-ky-trach-vu-nien-trinh-2024']/div/div[5]/div/div/div/label/button</value>
      <webElementGuid>d1d8a18a-a676-4b78-9aa0-832089ba77c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/button</value>
      <webElementGuid>96b2e36f-d77f-49c5-9b94-571305a3bd59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'data.hasConcurrentWork' and @type = 'button']</value>
      <webElementGuid>3e806ee7-35b6-4e6d-9704-25509810ea30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
