<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputdata_dkTNHD_kynangtinhoc</name>
   <tag></tag>
   <elementGuidId>f1f1ab26-39fc-4b40-b40a-8abbbab891ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='data.kynangtinhoc-Tin học căn bản']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd7e6364-eb44-49cc-a9cb-b31d76b00b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data.kynangtinhoc-Tin học căn bản</value>
      <webElementGuid>4c4e000d-ce08-436f-9fce-c1cab944c774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data.kynangtinhoc</value>
      <webElementGuid>ec839bd7-9bd6-49ce-96ac-02646e894f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>08c391d1-5b5e-4abf-b736-a5740bff77f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tin học căn bản</value>
      <webElementGuid>f9219e1d-f51a-489a-880d-ab09ebf79b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:loading.attr</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>6c021624-e9a9-4014-94b1-683990b8a1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model</name>
      <type>Main</type>
      <value>data.kynangtinhoc</value>
      <webElementGuid>c1604e02-b9ad-4cc0-9f69-839f6b12ec17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 border-none bg-white shadow-sm ring-1 transition duration-75 checked:ring-0 focus:ring-2 focus:ring-offset-0 disabled:bg-gray-50 disabled:text-gray-50 disabled:checked:bg-current disabled:checked:text-gray-400 dark:bg-white/5 dark:disabled:bg-transparent dark:disabled:checked:bg-gray-600 text-danger-600 ring-danger-600 focus:ring-danger-600 checked:focus:ring-danger-500/50 dark:text-danger-500 dark:ring-danger-500 dark:checked:bg-danger-500 dark:focus:ring-danger-500 dark:checked:focus:ring-danger-400/50</value>
      <webElementGuid>6a76a6fb-2350-4a0e-a6d8-2af5af8c03e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data.kynangtinhoc-Tin học căn bản&quot;)</value>
      <webElementGuid>df6b8e01-e748-4390-bfa0-16e19ad62262</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='data.kynangtinhoc-Tin học căn bản']</value>
      <webElementGuid>06e7ba77-e908-4ca1-9a38-121abf0a8040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='data.ky-nang-chuyen-mon']/div/div/div/div[2]/div/div/div/fieldset/div/div/div/div/div[2]/div/div/label/input</value>
      <webElementGuid>977bc477-6d9c-4395-a895-928bbd20a98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/fieldset/div/div/div/div/div[2]/div/div/label/input</value>
      <webElementGuid>fa2bfab7-4c83-47b0-98e5-1150c8fc9ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'data.kynangtinhoc-Tin học căn bản' and @name = 'data.kynangtinhoc' and @type = 'radio']</value>
      <webElementGuid>7b3fd7a3-bf54-435c-8524-9d373cff03ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
