<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputdata_dkTNHD_traikyhientai_tunam</name>
   <tag></tag>
   <elementGuidId>77bba0d5-3b86-4452-8048-2d4fc89b543f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='data.traikyhientai_tunam']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7fcaccd-d4eb-4bd3-b54f-5a2d37022566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-input block w-full border-none py-1.5 text-base text-gray-950 transition duration-75 placeholder:text-gray-400 focus:ring-0 disabled:text-gray-500 disabled:[-webkit-text-fill-color:theme(colors.gray.500)] disabled:placeholder:[-webkit-text-fill-color:theme(colors.gray.400)] dark:text-white dark:placeholder:text-gray-500 dark:disabled:text-gray-400 dark:disabled:[-webkit-text-fill-color:theme(colors.gray.400)] dark:disabled:placeholder:[-webkit-text-fill-color:theme(colors.gray.500)] sm:text-sm sm:leading-6 bg-white/0 ps-3 pe-3</value>
      <webElementGuid>ab84329e-64be-4f42-b7c8-5b92fce452c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data.traikyhientai_tunam</value>
      <webElementGuid>67a01a93-b1fa-4249-9d78-5b7ee0518a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>YYYY</value>
      <webElementGuid>320e1366-501d-43e8-99db-fd73f018be8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>10df64cb-7063-487e-a129-0d74aefc5a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model</name>
      <type>Main</type>
      <value>data.traikyhientai_tunam</value>
      <webElementGuid>b9fd29fc-4985-4155-86d7-0dfbe7431951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-data</name>
      <type>Main</type>
      <value>{}</value>
      <webElementGuid>815f8751-17a9-4ae3-92c7-42d6b7fe9f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x-mask</name>
      <type>Main</type>
      <value>9999</value>
      <webElementGuid>5171bde1-15e9-4fb8-9587-25963a276168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-has-alpine-state</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4cb9633b-39bb-41fe-9e4e-5941f86e726c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data.traikyhientai_tunam&quot;)</value>
      <webElementGuid>41c0a05f-468c-4d4c-88c5-d3ff4a81ff3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='data.traikyhientai_tunam']</value>
      <webElementGuid>4b846fce-86ff-42a3-b131-ba7dd852bb37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='data.thong-tin-tu-hoc']/div/div/div/div/div/div/div[2]/fieldset/div/div[3]/div/div/div[2]/div/div/input</value>
      <webElementGuid>117ac91c-7b21-4a69-8326-6ea87d7ab87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div/div[3]/div/div/div[2]/div/div/input</value>
      <webElementGuid>6690d4a0-44a3-4dd0-b476-c519bad7811b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'data.traikyhientai_tunam' and @placeholder = 'YYYY' and @type = 'text']</value>
      <webElementGuid>6b0d7d03-3d18-49ed-b620-524bf6595f73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
