<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>inputdata_dkTNHD_trinhdohocvan</name>
   <tag></tag>
   <elementGuidId>7f6b1720-d31d-4d96-8640-e48d0cd8c485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='data.trinhdohocvan-Tốt nghiệp cấp 3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98f61a35-a485-40e8-84b5-b60bbb9e791c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>data.trinhdohocvan-Tốt nghiệp cấp 3</value>
      <webElementGuid>ef6b4aaa-8489-4631-9283-10622229bdf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>data.trinhdohocvan</value>
      <webElementGuid>3a19ead4-85ee-4208-8562-4c377d4460fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e380c8fb-a5fb-49e1-845e-aa7ca78e2c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tốt nghiệp cấp 3</value>
      <webElementGuid>8e9ad18b-1e2d-4ec4-878c-c370c3737ded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:loading.attr</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>5bdf6bfb-8f49-4627-bb2f-4079fdf63bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wire:model</name>
      <type>Main</type>
      <value>data.trinhdohocvan</value>
      <webElementGuid>57bd1182-afa2-4609-907c-3bd254bee9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-1 border-none bg-white shadow-sm ring-1 transition duration-75 checked:ring-0 focus:ring-2 focus:ring-offset-0 disabled:bg-gray-50 disabled:text-gray-50 disabled:checked:bg-current disabled:checked:text-gray-400 dark:bg-white/5 dark:disabled:bg-transparent dark:disabled:checked:bg-gray-600 text-primary-600 ring-gray-950/10 focus:ring-primary-600 checked:focus:ring-primary-500/50 dark:text-primary-500 dark:ring-white/20 dark:checked:bg-primary-500 dark:focus:ring-primary-500 dark:checked:focus:ring-primary-400/50 dark:disabled:ring-white/10</value>
      <webElementGuid>88ebd4f7-8d91-48be-8206-ca3436226fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;data.trinhdohocvan-Tốt nghiệp cấp 3&quot;)</value>
      <webElementGuid>706482b7-2b4b-4915-be36-2a8cfc3d066b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='data.trinhdohocvan-Tốt nghiệp cấp 3']</value>
      <webElementGuid>2eb1e1ee-7c9d-4736-ae7e-1e58a6add214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='data.ky-nang-chuyen-mon']/div/div/div/div/div/div/div/fieldset/div/div/div/div/div[2]/div/div/label/input</value>
      <webElementGuid>a3ef5037-8929-40b4-af56-31e46e93729f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/section/div/div/div/div/div/div/div/fieldset/div/div/div/div/div[2]/div/div/label/input</value>
      <webElementGuid>5a4d6c33-e3d6-401c-8414-692105687421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'data.trinhdohocvan-Tốt nghiệp cấp 3' and @name = 'data.trinhdohocvan' and @type = 'radio']</value>
      <webElementGuid>9dfac370-6d20-4372-9028-fb07089b529f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
