<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_user-avatar</name>
   <tag></tag>
   <elementGuidId>53fa9e95-e02a-4b51-9b12-8344224f0d41</elementGuidId>
   <imagePath></imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.fi-avatar.object-cover.object-center.fi-circular.rounded-full.h-9.w-9.fi-user-avatar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[2]/div[1]/nav[1]/div[2]/div[2]/div[1]/button[1]/img[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'https://ui-avatars.com/api/?name=A&amp;color=FFFFFF&amp;background=030712']</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c3ffe579-df56-43f9-be83-f029b2c272a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-avatar object-cover object-center fi-circular rounded-full h-9 w-9 fi-user-avatar</value>
      <webElementGuid>e31a1f24-506d-49b7-97bc-217b7c163984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ui-avatars.com/api/?name=A&amp;color=FFFFFF&amp;background=030712</value>
      <webElementGuid>d60d3541-96fc-45f2-a779-cc1ba35fa685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fi min-h-screen&quot;]/body[@class=&quot;fi-body min-h-screen bg-gray-50 font-normal text-gray-950 antialiased dark:bg-gray-950 dark:text-white&quot;]/div[@class=&quot;fi-layout flex min-h-screen w-full overflow-x-clip&quot;]/div[@class=&quot;fi-main-ctn w-screen flex-1 flex-col flex&quot;]/div[@class=&quot;fi-topbar sticky top-0 z-20 overflow-x-clip fi-topbar-with-navigation&quot;]/nav[@class=&quot;flex h-16 items-center gap-x-4 bg-white px-4 shadow-sm ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10 md:px-6 lg:px-8&quot;]/div[@class=&quot;ms-auto flex items-center gap-x-4&quot;]/div[@class=&quot;fi-dropdown fi-user-menu&quot;]/div[@class=&quot;fi-dropdown-trigger flex cursor-pointer&quot;]/button[1]/img[@class=&quot;fi-avatar object-cover object-center fi-circular rounded-full h-9 w-9 fi-user-avatar&quot;]</value>
      <webElementGuid>ac3f77f8-8249-4ecb-9333-7e9172df0f57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ui-avatars.com/api/?name=A&amp;color=FFFFFF&amp;background=030712')]</value>
      <webElementGuid>500e0088-f076-4eea-bc5e-339e3466ec84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>7536a1c6-4426-4666-ae93-228e67008174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ui-avatars.com/api/?name=A&amp;color=FFFFFF&amp;background=030712']</value>
      <webElementGuid>6dfef155-e4e1-4361-bdfc-9b2b0d31e5f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
