<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_user-avatar</name>
   <tag></tag>
   <elementGuidId>53fa9e95-e02a-4b51-9b12-8344224f0d41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[1]/div[2]/div[1]/nav[1]/div[2]/div[2]/div[1]/button[1]/img[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.fi-avatar.object-cover.object-center.fi-circular.rounded-full.h-9.w-9.fi-user-avatar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a66edc3d-fa48-4547-9677-26e8b28fe04c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-avatar object-cover object-center fi-circular rounded-full h-9 w-9 fi-user-avatar</value>
      <webElementGuid>66bc5bb6-72d2-4f14-b3fe-d48af352a3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ui-avatars.com/api/?name=A&amp;color=FFFFFF&amp;background=030712</value>
      <webElementGuid>d1057374-6c89-480f-9dcf-75512abc3b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fi min-h-screen&quot;]/body[@class=&quot;fi-body min-h-screen bg-gray-50 font-normal text-gray-950 antialiased dark:bg-gray-950 dark:text-white&quot;]/div[@class=&quot;fi-layout flex min-h-screen w-full overflow-x-clip&quot;]/div[@class=&quot;fi-main-ctn w-screen flex-1 flex-col flex&quot;]/div[@class=&quot;fi-topbar sticky top-0 z-20 overflow-x-clip fi-topbar-with-navigation&quot;]/nav[@class=&quot;flex h-16 items-center gap-x-4 bg-white px-4 shadow-sm ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10 md:px-6 lg:px-8&quot;]/div[@class=&quot;ms-auto flex items-center gap-x-4&quot;]/div[@class=&quot;fi-dropdown fi-user-menu&quot;]/div[@class=&quot;fi-dropdown-trigger flex cursor-pointer&quot;]/button[1]/img[@class=&quot;fi-avatar object-cover object-center fi-circular rounded-full h-9 w-9 fi-user-avatar&quot;]</value>
      <webElementGuid>839f4101-ad93-46ff-bddd-3b041be99706</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ui-avatars.com/api/?name=A&amp;color=FFFFFF&amp;background=030712')]</value>
      <webElementGuid>cb281263-afd7-4b5b-80cc-2e0cc8a68bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>b843aeb5-d99c-487b-b78b-5b45a9cc7a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ui-avatars.com/api/?name=A&amp;color=FFFFFF&amp;background=030712']</value>
      <webElementGuid>8c59be89-0da1-4ca2-b746-0e2cd78b718c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
