<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Avatar</name>
   <tag></tag>
   <elementGuidId>c0c26840-c9fb-4c66-8b2d-1681c6146c9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,'https://ui-avatars.com/api/?name=T+L+K&amp;color=FFFFFF&amp;background=030712')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.fi-avatar.object-cover.object-center.fi-circular.rounded-full.h-9.w-9.fi-user-avatar</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c750e18e-d9df-4b3a-b232-cd2a8312981d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-avatar object-cover object-center fi-circular rounded-full h-9 w-9 fi-user-avatar</value>
      <webElementGuid>2eb7ab71-f3b3-48d9-aa81-30d091bd6dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://ui-avatars.com/api/?name=T+L+K&amp;color=FFFFFF&amp;background=030712</value>
      <webElementGuid>d2ba6333-d2bb-4f2a-8980-a53b271434ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fi min-h-screen&quot;]/body[@class=&quot;fi-body min-h-screen bg-gray-50 font-normal text-gray-950 antialiased dark:bg-gray-950 dark:text-white&quot;]/div[@class=&quot;fi-layout flex min-h-screen w-full overflow-x-clip&quot;]/div[@class=&quot;fi-main-ctn w-screen flex-1 flex-col flex&quot;]/div[@class=&quot;fi-topbar sticky top-0 z-20 overflow-x-clip fi-topbar-with-navigation&quot;]/nav[@class=&quot;flex h-16 items-center gap-x-4 bg-white px-4 shadow-sm ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10 md:px-6 lg:px-8&quot;]/div[@class=&quot;ms-auto flex items-center gap-x-4&quot;]/div[@class=&quot;fi-dropdown fi-user-menu&quot;]/div[@class=&quot;fi-dropdown-trigger flex cursor-pointer&quot;]/button[1]/img[@class=&quot;fi-avatar object-cover object-center fi-circular rounded-full h-9 w-9 fi-user-avatar&quot;]</value>
      <webElementGuid>3c5e0f61-1685-4a79-86f2-208bc6e38efd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://ui-avatars.com/api/?name=T+L+K&amp;color=FFFFFF&amp;background=030712')]</value>
      <webElementGuid>8e349167-054c-41f1-8115-ddad53098be7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>cc169603-a25c-428b-9014-eb346473b333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://ui-avatars.com/api/?name=T+L+K&amp;color=FFFFFF&amp;background=030712']</value>
      <webElementGuid>a2fdc63f-8106-4cc5-a1e0-afb1f0a52da5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
