<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_fi-icon-btn-icon h-6 w-6</name>
   <tag></tag>
   <elementGuidId>39d26972-9c3e-43ae-935b-5d673e35a136</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>eb5a9b28-4ff5-487b-b389-682a16786499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fi-icon-btn-icon h-6 w-6</value>
      <webElementGuid>70d9f9a5-b153-4d3f-a155-e4144460c558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>75e3348e-a768-483d-8c2c-6039994383f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>699f241f-6d4d-4746-9951-7cdc0f43b88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>41328427-8f64-4abf-a229-9c8ae4090768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>1.5</value>
      <webElementGuid>6c20f2b0-ec1e-4d22-a01a-2405e68ac9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>83746671-efa6-44b2-a9ef-5f26254b6ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>218b6781-639a-4dc7-872b-65e500b43ddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;fi min-h-screen&quot;]/body[@class=&quot;fi-body min-h-screen bg-gray-50 font-normal text-gray-950 antialiased dark:bg-gray-950 dark:text-white&quot;]/div[@class=&quot;fi-layout flex min-h-screen w-full overflow-x-clip&quot;]/div[@class=&quot;fi-main-ctn w-screen flex-1 flex-col flex&quot;]/div[@class=&quot;fi-topbar sticky top-0 z-20 overflow-x-clip fi-topbar-with-navigation&quot;]/nav[@class=&quot;flex h-16 items-center gap-x-4 bg-white px-4 shadow-sm ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10 md:px-6 lg:px-8&quot;]/div[@class=&quot;ms-auto flex items-center gap-x-4&quot;]/div[@class=&quot;flex&quot;]/div[@class=&quot;fi-modal inline-block&quot;]/div[@class=&quot;fixed inset-0 z-40 min-h-full overflow-y-auto overflow-x-hidden transition&quot;]/div[@class=&quot;pointer-events-none relative w-full transition&quot;]/div[@class=&quot;fi-modal-window pointer-events-auto relative flex w-full cursor-default flex-col bg-white shadow-xl ring-1 ring-gray-950/5 dark:bg-gray-900 dark:ring-white/10 fi-modal-slide-over-window ms-auto overflow-y-auto h-screen max-w-md&quot;]/div[@class=&quot;fi-modal-header flex px-6 pt-6 fi-sticky sticky top-0 z-10 border-b border-gray-200 bg-white pb-6 dark:border-white/10 dark:bg-gray-900 gap-x-5&quot;]/div[@class=&quot;absolute end-6 top-6&quot;]/button[@class=&quot;fi-icon-btn relative flex items-center justify-center rounded-lg outline-none transition duration-75 focus-visible:ring-2 disabled:pointer-events-none disabled:opacity-70 -m-1.5 h-9 w-9 fi-color-gray text-gray-400 hover:text-gray-500 focus-visible:ring-primary-600 dark:text-gray-500 dark:hover:text-gray-400 dark:focus-visible:ring-primary-500 fi-modal-close-btn katalonDeHighlight&quot;]/svg[@class=&quot;fi-icon-btn-icon h-6 w-6&quot;]</value>
      <webElementGuid>b11916ae-fe0d-4bf0-b77f-3e32297f9f22</webElementGuid>
   </webElementProperties>
</WebElementEntity>
